backend = "glx";
vsync = true;

inactive-opacity = 0.90;
active-opacity = 1.0;
frame-opacity = 0.9;
inactive-opacity-override = false;

use-damage = true;
unredir-if-possible = false;

shadow = false;
fading = false;
fade-in-step = 0.03;
fade-out-step = 0.03;

detect-client-opacity = true;

